//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mechanic_Motors.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public int IdPieza { get; set; }
        public string NombrePieza { get; set; }
        public string VehiculoPerteneciente { get; set; }
        public string Color { get; set; }
        public double PrecioUnitario { get; set; }
        public int Cantidad { get; set; }
    }
}
